---
- import_tasks: "setup-RedHat.yml"
  when:
    - ansible_os_family == 'RedHat'

- import_tasks: "setup-Debian.yml"
  when:
    - ansible_os_family == 'Debian'

- name: GPG key Install
  shell: |
     #gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
     curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
     curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
  become: true

- name: Install RVM Mixed Mode
  shell: |
     curl -sSL https://get.rvm.io | bash -s stable
  become: true

- name: Add user to rvm group
  shell: |
     usermod -a -G rvm {{ ruby_username }}
  become: true

- name: Install Ruby {{ ruby_version }}
  shell: |
     bash -lc "rvm install {{ ruby_version }}"
     bash -lc "rvm use {{ ruby_version }} --default"
  become: true
