---
- name: Install rke2
  become: yes
  become_user: ubuntu 
  shell: curl -sfL https://get.rke2.io | sudo sh - 

- name: Install Helm
  become: yes
  become_user: ubuntu 
  shell: curl -L https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    
- name: Enable Service 
  systemd:
     name: rke2-server
     state: restarted
     daemon_reload: yes
  register: rke2_service
  until: rke2_service.status.ActiveState == "active"
  retries: 15
  delay: 20
