---
- name: Install GitHub Actions Base
  hosts: actions_runner
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "../../inventory/group_vars/all.yml"
  roles:
  - role: general
  - role: docker/ubuntu/common
    when: ansible_os_family == 'Debian'
  - role: docker/ubuntu/install
    when: ansible_os_family == 'Debian'
  - role: github-actions
    when: ansible_os_family == 'Debian'
