# Get GPG Key for Docker
- name: Install few requirements
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Get docker gpg keys
  apt_key: 
     url: "https://download.docker.com/linux/ubuntu/gpg" 
     state: present

- name: Create sources.list.d
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: 'docker.list'      

- name: Refresh apt cache
  apt:
      update_cache: yes
