---
- name: Install k3 Base
  hosts: k3s_master
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "../../inventory/group_vars/all.yml"
  tasks:
    - name: Display K3s Token
      command: cat node-token
      args: 
        chdir: /var/lib/rancher/k3s/server
      register: k3s_token_output

    - name: Print K3s to console
      debug:
         msg: "{{k3s_token_output.stdout}}"

    - name: Print Server IP
      debug:
         msg: "{{hostvars[groups['k3s_master'][0]]['ansible_default_ipv4']['address']}}"

    - name: set server token 
      set_fact:
        k3s_token: "{{ k3s_token_output.stdout }}"
        k3s_server_ip: "{{hostvars[groups['k3s_master'][0]]['ansible_default_ipv4']['address']}}"



- name: Install k3 Nodes
  hosts: k3s_nodes
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - "../../inventory/group_vars/all.yml"
  tasks:
    - name: Install & Register Nodes
      shell: curl -sfL http://get.k3s.io | K3S_URL=https://{{ hostvars['kube-master'].k3s_server_ip }}:6443 K3S_TOKEN={{ hostvars['kube-master'].k3s_token }} sh -

    - name: Enable Service 
      systemd:
         name: k3s-agent
         state: restarted
         daemon_reload: yes
      register: k3s_agent_service
      until: k3s_agent_service.status.ActiveState == "active"
      retries: 15
      delay: 20
