---
- name: Install rke2 Base
  hosts: rke2_stack
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: general
  - role: docker/ubuntu/common
    when: ansible_os_family == 'Debian'
  - role: docker/ubuntu/install
    when: ansible_os_family == 'Debian'
