---
- name: Install rke2 master
  hosts: rke2_master
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: rke2/master
    when: ansible_os_family == 'Debian'
