---
ansible_connection: ssh
ansible_user: ubuntu
ansible_python_interpreter: 'python3'

docker_machine_version: "v0.12.2"
docker_machine_url: "https://github.com/docker/machine/releases/download/{{ docker_machine_version }}/docker-machine-{{ ansible_system }}-{{ ansible_machine }}"
